### ISSUE TITLE
Is the State of HTML 2023 survey available in light mode?

### ISSUE THREAD

**Issue by simevidas** [Devographics/Monorepo#309]
https://lea.verou.me/blog/2023/state-of-html-2023/

I have trouble reading text in dark mode. The survey renders in dark mode. I don’t see a control to switch to light mode. My CSS `prefers-color-scheme` preference is `light`. 

edit: In the meantime, I’m using the following user style to emulate a light mode for your website:

```css
@media (prefers-color-scheme: light) {
    html {
        filter: hue-rotate(180deg) invert(1);
        color-scheme: light;
    }

    img, video, picture {
        filter: hue-rotate(180deg) invert(1);
    }
}
```

(code by @kizu)
